version: "3.8"
services:
  pg-db:
    image: postgres:17.4-alpine
    container_name: pg-db
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 30s
      retries: 5

volumes:
  pg_data:
    name: pg_data